[build]
  command = "npm run build"
  publish = "app/client/dist"
  functions = "app/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
      external_node_modules = ["wink-bm25-text-search", "csv-parse", "pino"]
